name: yts_dbt_project
version: 1.0.0
config-version: 2
profile: yts_dbt

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  yts_dbt_project:
    +materialized: view
