global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets:
          - yts-proxy:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - yts-cadvisor:8080
